from flask import Flask, request, jsonify
from banyan import * # need to apply this patch! https://code.google.com/p/banyan/issues/detail?id=5
from itertools import *

import json
import pprint

app = Flask(__name__)
pp = pprint.PrettyPrinter(indent=4)

@app.route('/')
def root():
    return app.send_static_file('index.html')

@app.route('/annotate', methods=['POST'])
def annotate():
    textContents = json.loads(request.data) # generated by pdf.js
    # we need to do two things, create a single string for each page
    # and establish a interval-tree to figure out the original nodes

    return jsonify({"annotations" : []});

if __name__ == "__main__":
    app.run(debug=True)
