from flask import Flask, request, jsonify
from pipeline import MockPipeline
import json

app = Flask(__name__)
pipeline = MockPipeline()

@app.route('/')
def root():
    return app.send_static_file('index.html')

@app.route('/annotate', methods=['POST'])
def annotate():
    payload = json.loads(request.data) # generated by pdf.js, per page
    result = pipeline.predict(payload)
    return jsonify(result);

if __name__ == "__main__":
    app.run(debug=True)
